import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    "introduction",
    // {
    //   type: "category",
    //   label: "Getting Started",
    //   link: {
    //     type: "doc",
    //     id: "getting-started/index",
    //   },
    //   items: [
    //     "getting-started/loon-wrappers",
    //     "getting-started/building-loon",
    //     "getting-started/data",
    //   ],
    // },
    // {
    //   type: "category",
    //   label: "How-To-Guides",
    //   link: {
    //     type: "generated-index",
    //   },
    //   items: ["how-to-guides/working-with-minio"],
    // },
    {
      type: "category",
      label: "How To Use Loon",
      link: {
        type: "doc",
        id: "how-to-use-loon/index",
      },
      items: [
        "how-to-use-loon/quickstart",
        "how-to-use-loon/data",
        "how-to-use-loon/loon-wrappers",
        "how-to-use-loon/working-with-minio",
        "how-to-use-loon/trackmate-data",
      ],
    },
    {
      type: "category",
      label: "Help Develop Loon",
      link: {
        type: "doc",
        id: "help-develop-loon/index",
      },
      items: [
        "help-develop-loon/quickstart",
        "help-develop-loon/building-loon",
      ],
    },
  ],
};

export default sidebars;
