import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    "introduction",
    {
      type: "category",
      label: "Getting Started",
      link: {
        type: "doc",
        id: "getting-started-with-loon/index",
      },
      items: [
        {type: "category", label: "Prepare Your Data", link: {type: "doc", id: "getting-started-with-loon/data",}, items: [
        "getting-started-with-loon/trackmate-data",]},
        "getting-started-with-loon/quickstart",
        { 
          type: "category", 
          label: "Extra Resources", 
          link: { type: "generated-index" },
          items: [
            "troubleshooting-docker",
            "getting-started-with-loon/working-with-minio",
          ],
        },
      ],
    },
    {
      type: "html",
      value: '<hr style="border: 0.5px solid #ddd; margin: 0.5rem 0;" />',
    },
    "version-log",
    "help-develop-loon/index",
  ],
};

export default sidebars;
